packages:
  - "."
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  core-js: set this to true or false
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - astro@7.2.2

onlyBuiltDependencies:
  - sharp

supportedArchitectures:
  os:
    - win32
    - linux
  cpu:
    - x64
